create table if not exists public.invite_codes (
  id bigint generated by default as identity primary key,
  email text not null,
  code_hash text not null unique,
  code_last4 text not null,
  created_by uuid not null references auth.users (id) on delete cascade,
  used_by_user_id uuid references auth.users (id) on delete set null,
  expires_at timestamptz not null default (now() + interval '7 days'),
  used_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists invite_codes_email_idx
  on public.invite_codes (lower(email));

create index if not exists invite_codes_created_by_idx
  on public.invite_codes (created_by);

create index if not exists invite_codes_expires_at_idx
  on public.invite_codes (expires_at);

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  role text not null default 'member' check (role in ('owner', 'member')),
  invited_by uuid references auth.users (id) on delete set null,
  invite_code_id bigint references public.invite_codes (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_email_unique_idx
  on public.profiles (lower(email));

create index if not exists profiles_role_idx
  on public.profiles (role);

create or replace function public.set_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at
  on public.profiles;

create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_profiles_updated_at();

insert into public.profiles (
  id,
  email,
  role,
  created_at,
  updated_at
)
select
  users.id,
  lower(users.email),
  'member',
  coalesce(users.created_at, now()),
  coalesce(users.updated_at, users.created_at, now())
from auth.users as users
where users.email is not null
on conflict (id) do update
set email = excluded.email,
    updated_at = greatest(public.profiles.updated_at, excluded.updated_at);

do $$
begin
  if not exists (
    select 1
    from public.profiles
    where role = 'owner'
  ) then
    update public.profiles
    set role = 'owner'
    where id = (
      select id
      from public.profiles
      order by created_at asc, id asc
      limit 1
    );
  end if;
end $$;

alter table public.profiles enable row level security;
alter table public.invite_codes enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'profiles'
      and policyname = 'profiles_select_own'
  ) then
    create policy profiles_select_own
      on public.profiles
      for select
      using (auth.uid() = id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'profiles'
      and policyname = 'profiles_update_own'
  ) then
    create policy profiles_update_own
      on public.profiles
      for update
      using (auth.uid() = id)
      with check (auth.uid() = id);
  end if;
end $$;
