create table if not exists public.staff_compensation_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  staff_name text not null,
  fixed_salary numeric(12,2) not null default 0,
  bonus_rate numeric(5,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, staff_name)
);

create index if not exists staff_compensation_settings_user_id_idx
  on public.staff_compensation_settings (user_id);

create index if not exists staff_compensation_settings_staff_name_idx
  on public.staff_compensation_settings (staff_name);

create or replace function public.set_staff_compensation_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_staff_compensation_settings_updated_at
  on public.staff_compensation_settings;

create trigger set_staff_compensation_settings_updated_at
before update on public.staff_compensation_settings
for each row
execute function public.set_staff_compensation_settings_updated_at();

alter table public.staff_compensation_settings enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'staff_compensation_settings'
      and policyname = 'staff_compensation_settings_select_own'
  ) then
    create policy staff_compensation_settings_select_own
      on public.staff_compensation_settings
      for select
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'staff_compensation_settings'
      and policyname = 'staff_compensation_settings_insert_own'
  ) then
    create policy staff_compensation_settings_insert_own
      on public.staff_compensation_settings
      for insert
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'staff_compensation_settings'
      and policyname = 'staff_compensation_settings_update_own'
  ) then
    create policy staff_compensation_settings_update_own
      on public.staff_compensation_settings
      for update
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'staff_compensation_settings'
      and policyname = 'staff_compensation_settings_delete_own'
  ) then
    create policy staff_compensation_settings_delete_own
      on public.staff_compensation_settings
      for delete
      using (auth.uid() = user_id);
  end if;
end $$;
