create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  customer text not null,
  phone text,
  created_at timestamptz not null default now()
);

create index if not exists customers_user_id_idx
  on public.customers (user_id);

alter table public.customers enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'customers'
      and policyname = 'customers_select_own'
  ) then
    create policy customers_select_own
      on public.customers
      for select
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'customers'
      and policyname = 'customers_insert_own'
  ) then
    create policy customers_insert_own
      on public.customers
      for insert
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'customers'
      and policyname = 'customers_update_own'
  ) then
    create policy customers_update_own
      on public.customers
      for update
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'customers'
      and policyname = 'customers_delete_own'
  ) then
    create policy customers_delete_own
      on public.customers
      for delete
      using (auth.uid() = user_id);
  end if;
end $$;

