create table if not exists public.products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  product text not null,
  transaction_type text,
  counterparty text,
  category text,
  cost_price text,
  price text,
  stock text,
  created_at timestamptz not null default now()
);

create index if not exists products_user_id_idx
  on public.products (user_id);

create index if not exists products_product_idx
  on public.products (product);

alter table public.products enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'products'
      and policyname = 'products_select_own'
  ) then
    create policy products_select_own
      on public.products
      for select
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'products'
      and policyname = 'products_insert_own'
  ) then
    create policy products_insert_own
      on public.products
      for insert
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'products'
      and policyname = 'products_update_own'
  ) then
    create policy products_update_own
      on public.products
      for update
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'products'
      and policyname = 'products_delete_own'
  ) then
    create policy products_delete_own
      on public.products
      for delete
      using (auth.uid() = user_id);
  end if;
end $$;
