create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  customer text,
  phone text,
  service text not null,
  staff text,
  date date,
  time time,
  status text not null default 'Taslak',
  total_price text,
  creator text,
  created_at timestamptz not null default now()
);

create index if not exists appointments_user_id_idx
  on public.appointments (user_id);

create index if not exists appointments_date_time_idx
  on public.appointments (date, time);

alter table public.appointments enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'appointments'
      and policyname = 'appointments_select_own'
  ) then
    create policy appointments_select_own
      on public.appointments
      for select
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'appointments'
      and policyname = 'appointments_insert_own'
  ) then
    create policy appointments_insert_own
      on public.appointments
      for insert
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'appointments'
      and policyname = 'appointments_update_own'
  ) then
    create policy appointments_update_own
      on public.appointments
      for update
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'appointments'
      and policyname = 'appointments_delete_own'
  ) then
    create policy appointments_delete_own
      on public.appointments
      for delete
      using (auth.uid() = user_id);
  end if;
end $$;

insert into public.appointments (
  user_id,
  customer,
  phone,
  service,
  staff,
  date,
  time,
  status,
  total_price,
  creator,
  created_at
)
select
  n.user_id,
  nullif(n.content::jsonb ->> 'customer', ''),
  nullif(n.content::jsonb ->> 'phone', ''),
  coalesce(nullif(n.content::jsonb ->> 'service', ''), n.content),
  nullif(n.content::jsonb ->> 'staff', ''),
  nullif(n.content::jsonb ->> 'date', '')::date,
  nullif(n.content::jsonb ->> 'time', '')::time,
  coalesce(nullif(n.content::jsonb ->> 'status', ''), 'Taslak'),
  nullif(n.content::jsonb ->> 'totalPrice', ''),
  nullif(n.content::jsonb ->> 'creator', ''),
  n.created_at
from public.notes n
where not exists (
  select 1
  from public.appointments a
  where a.user_id = n.user_id
    and a.service = coalesce(nullif(n.content::jsonb ->> 'service', ''), n.content)
    and a.created_at = n.created_at
);
