create table if not exists public.package_sales (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  customer text not null,
  phone text,
  package_name text not null,
  session_type text not null,
  total_sessions integer not null default 1,
  used_sessions integer not null default 0,
  price text,
  created_at timestamptz not null default now()
);

create index if not exists package_sales_user_id_idx
  on public.package_sales (user_id);

create index if not exists package_sales_customer_idx
  on public.package_sales (customer);

alter table public.package_sales enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'package_sales'
      and policyname = 'package_sales_select_own'
  ) then
    create policy package_sales_select_own
      on public.package_sales
      for select
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'package_sales'
      and policyname = 'package_sales_insert_own'
  ) then
    create policy package_sales_insert_own
      on public.package_sales
      for insert
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'package_sales'
      and policyname = 'package_sales_update_own'
  ) then
    create policy package_sales_update_own
      on public.package_sales
      for update
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'package_sales'
      and policyname = 'package_sales_delete_own'
  ) then
    create policy package_sales_delete_own
      on public.package_sales
      for delete
      using (auth.uid() = user_id);
  end if;
end $$;
