create table if not exists public.staff_members (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create index if not exists staff_members_user_id_idx
  on public.staff_members (user_id);

create index if not exists staff_members_name_idx
  on public.staff_members (name);

alter table public.staff_members enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'staff_members'
      and policyname = 'staff_members_select_own'
  ) then
    create policy staff_members_select_own
      on public.staff_members
      for select
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'staff_members'
      and policyname = 'staff_members_insert_own'
  ) then
    create policy staff_members_insert_own
      on public.staff_members
      for insert
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'staff_members'
      and policyname = 'staff_members_update_own'
  ) then
    create policy staff_members_update_own
      on public.staff_members
      for update
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'staff_members'
      and policyname = 'staff_members_delete_own'
  ) then
    create policy staff_members_delete_own
      on public.staff_members
      for delete
      using (auth.uid() = user_id);
  end if;
end $$;

insert into public.staff_members (user_id, name)
select distinct
  appointments.user_id,
  trim(appointments.staff)
from public.appointments as appointments
where appointments.staff is not null
  and trim(appointments.staff) <> ''
on conflict (user_id, name) do nothing;
